workflows:
  android-deploy-workflow:
    name: Android Deployment Workflow
    instance_type: mac_mini_m1
    max_build_duration: 30
    triggering:
      events:
        - push
        - pull_request
      branch_patterns:
        - pattern: 'test'
          include: true
          source: false 
      cancel_previous_builds: true
    environment:
      groups:
        - google_credentials
      flutter: stable
      xcode: latest
      cocoapods: default
    scripts:
      - name: Setup the keystore
        script: |
          echo $KEYSTORE_FILE | base64 --decode > /tmp/keystore.jks
          cat > "$CM_BUILD_DIR/android/key.properties" << EOF
          storePassword=$KEYSTORE_PASSWORD
          keyPassword=$KEYSTORE_KEY_PASSWORD
          keyAlias=upload
          storeFile=/tmp/keystore.jks
          EOF
      - name: Create .env file
        script: |
          echo "$TEXTO" > "$CM_BUILD_DIR/.env"
      - name: Build AAB
        script: |
          cd $CM_BUILD_DIR
          CURRENT_BUILD_NUMBER=$(google-play get-latest-build-number --package-name "com.codemagic_test.app" --tracks="alpha" || cat $CM_BUILD_DIR/version_code.txt)
          echo "Retrieved Build Number: $CURRENT_BUILD_NUMBER"
          NEW_BUILD_NUMBER=$(($CURRENT_BUILD_NUMBER + 1))
          echo $NEW_BUILD_NUMBER > $CM_BUILD_DIR/version_code.txt
          echo "New Build Number: $NEW_BUILD_NUMBER"
          flutter pub get
          flutter build appbundle --release --build-number=$NEW_BUILD_NUMBER
    artifacts:
      - build/**/outputs/**/*.aab
    publishing:
      google_play:
        credentials: $GCLOUD_SERVICE_ACCOUNT_CREDENTIALS
        track: internal
        submit_as_draft: true